- hosts: landing-page
  remote_user: ubuntu
  become: yes
  become_method: sudo
  tasks:
    - name: install apache2
      apt:
        name: apache2
        state: latest
    - name: start apache service
      service:
        name: apache2
        state: started
    - name: deploy landing-page to /var/www/html/
      copy:
        src: /tmp/landing-page/
        dest: /var/www/html/
