- hosts: landing-page
  vars:
    http_port: 8081
  remote_user: ubuntu
  become: yes
  become_method: sudo
  tasks:
    - name: install apache2
      apt:
        name: apache2
        state: latest
    - name: start apache service
      service:
        name: apache2
        state: started
    - name: deploy landing-page to /var/www/html/
      copy:
        src: /tmp/landing-page/
        dest: /var/www/html/
    - name: deploy konfigurasi port apache2
      template:
        src: /root/cilsy-ansible/ports.conf.j2
        dest: /etc/apache2/ports.conf
      notify: restart_apache2
  handlers:
    - name: restart_apache2
      service:
        name: apache2
        state: restarted
