- name: install apache2
  apt:
    name: apache2
    state: latest

- name: start apache2 service
  service:
    name: apache2
    state: started

- name: ubah konfigurasi port
  template:
    src: ports.conf.j2
    dest: /etc/apache2/ports.conf
  notify: restart apache2

- name: deploy landingpage
  copy:
    src: /tmp/landingpage/
    dest: /var/www/html/
  notify: restart apache2
